package com.pptxgenerator.common.ai;

import com.pptxgenerator.client.dto.JsonSchemaDto;
import com.pptxgenerator.model.Zone;
import com.pptxgenerator.model.ZoneKeys;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Single source of truth for the JSON output schemas used by every pipeline step.
 *
 * <p>Each method returns a {@link JsonSchemaDto}, the type actually honoured by the AI
 * gateway ({@code instanceof JsonSchemaDto}), so the schemas are really enforced by the
 * provider instead of being ignored.
 *
 * <ul>
 *   <li>{@link #createPlanSchema()} — M2 planning (plan narrative);</li>
 *   <li>{@link #createLayoutSchema()} — M3 layout assignment;</li>
 *   <li>{@link #createSlideContentSchema(List)} — M4 content generation, one string
 *       property per zone key ({@code zone_type_zone_id}).</li>
 * </ul>
 */
public final class OutputSchemaProvider {

    private OutputSchemaProvider() {
    }

    /**
     * Schema of the plan narrative generated by the planning step (M2).
     */
    public static JsonSchemaDto createPlanSchema() {
        Map<String, JsonSchemaDto> slideProps = new LinkedHashMap<>();
        slideProps.put("slide_number", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.INTEGER).build());
        slideProps.put("slide_type", JsonSchemaDto.builder()
                .type(JsonSchemaDto.TypeEnum.STRING)
                .enum_(List.of("title", "outline", "section_transition", "content"))
                .build());
        slideProps.put("purpose", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        slideProps.put("content_brief", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        slideProps.put("detailed_context", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        slideProps.put("section_number", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.INTEGER).build());
        slideProps.put("section_title", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());

        Map<String, JsonSchemaDto> planProps = new LinkedHashMap<>();
        planProps.put("title", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        planProps.put("narrative_arc", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        planProps.put("total_slides", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.INTEGER).build());
        planProps.put("slides", JsonSchemaDto.builder()
                .type(JsonSchemaDto.TypeEnum.ARRAY)
                .items(JsonSchemaDto.builder()
                        .type(JsonSchemaDto.TypeEnum.OBJECT)
                        .properties(slideProps)
                        .required(List.of("slide_number", "slide_type", "purpose", "content_brief", "detailed_context"))
                        .build())
                .build());

        return JsonSchemaDto.builder()
                .type(JsonSchemaDto.TypeEnum.OBJECT)
                .properties(Map.of("presentation_plan", JsonSchemaDto.builder()
                        .type(JsonSchemaDto.TypeEnum.OBJECT)
                        .properties(planProps)
                        .required(List.of("title", "narrative_arc", "total_slides", "slides"))
                        .build()))
                .required(List.of("presentation_plan"))
                .build();
    }

    /**
     * Schema of the layout selection returned by the layout assignment step (M3).
     */
    public static JsonSchemaDto createLayoutSchema() {
        Map<String, JsonSchemaDto> properties = new LinkedHashMap<>();
        properties.put("layout_id", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        properties.put("rationale", JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
        return JsonSchemaDto.builder()
                .type(JsonSchemaDto.TypeEnum.OBJECT)
                .properties(properties)
                .required(List.of("layout_id", "rationale"))
                .build();
    }

    /**
     * Schema of a content slide (M4): one string property per zone key.
     *
     * @param layoutZones the zones of the slide layout; may be null or empty
     */
    public static JsonSchemaDto createSlideContentSchema(List<Zone> layoutZones) {
        Map<String, JsonSchemaDto> properties = new LinkedHashMap<>();
        if (layoutZones != null) {
            for (Zone zone : layoutZones) {
                properties.put(ZoneKeys.key(zone), JsonSchemaDto.builder().type(JsonSchemaDto.TypeEnum.STRING).build());
            }
        }
        return JsonSchemaDto.builder()
                .type(JsonSchemaDto.TypeEnum.OBJECT)
                .properties(properties)
                .required(List.copyOf(properties.keySet()))
                .build();
    }
}
